name: commentor
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  get: ^4.3.8
  carousel_slider: ^4.0.0
  image_picker: ^0.8.4+4
  logger: ^1.1.0
  image_cropper: ^1.4.1
  firebase_core: "^1.10.0"
  firebase_storage: "^10.1.0"
  google_sign_in: ^5.2.1
  firebase_auth: ^3.2.0
  cloud_firestore:
  timeago: ^3.1.0
  cached_network_image: ^3.1.0+1
  persistent_bottom_nav_bar: ^4.0.2
  sizer: ^2.0.15
  like_button: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
